=== Apress/msft-office-programming/Ch10/CustomersSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="Customers"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="Customers">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CustomerNumber" index-key="CustomerNumber " primary="no" unique="yes" clustered="no"/>
<od:index index-name="PrimaryKey" index-key="CustomerNumber " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="CompanyName" index-key="CompanyName " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CompanyName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CustomerNumber" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Apress/msft-office-programming/Ch10/Customers.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="CustomersSchema.xsd">
<Customers>
<CompanyName>PZVUYFPPUK</CompanyName>
<CustomerNumber>21</CustomerNumber>
</Customers>
<Customers>
<CompanyName>GBDRCLMHPZ</CompanyName>
<CustomerNumber>22</CustomerNumber>
</Customers>
<Customers>
<CompanyName>EYHDXCVNFF</CompanyName>
<CustomerNumber>23</CustomerNumber>
</Customers>
<Customers>
<CompanyName>MKUNDKFDVA</CompanyName>
<CustomerNumber>24</CustomerNumber>
</Customers>
<Customers>
<CompanyName>VQBSNPBAXZ</CompanyName>
<CustomerNumber>25</CustomerNumber>
</Customers>
<Customers>
<CompanyName>URKBCSMSUX</CompanyName>
<CustomerNumber>26</CustomerNumber>
</Customers>
<Customers>
<CompanyName>TFVYVWOHXZ</CompanyName>
<CustomerNumber>27</CustomerNumber>
</Customers>
<Customers>
<CompanyName>HBBVEGCCHG</CompanyName>
<CustomerNumber>28</CustomerNumber>
</Customers>
<Customers>
<CompanyName>SGGRYKJZJO</CompanyName>
<CustomerNumber>29</CustomerNumber>
</Customers>
<Customers>
<CompanyName>KMHWMFFWOG</CompanyName>
<CustomerNumber>30</CustomerNumber>
</Customers>
</dataroot>
